### ISSUE TITLE
O(n) instead of O(n^2) for TableRenderer.CreateNextBottomBorderPosition()

### ISSUE THREAD

**Issue by groege** [empira/MigraDoc-1.5#14]
If you think there is a bug in MigraDoc then please use the IssueSubmissionTemplate to make the issue replicable.  
http://www.pdfsharp.net/wiki/IssueSubmissions.ashx

Thanks.

# Resources

The official project web site:  
http://pdfsharp.net/

The official peer-to-peer support forum:  
http://forum.pdfsharp.net/

# Reporting an Issue Here
## Steps to Reproduce the Behavior
We strongly recommend using the IssueSubmissionTemplate to make sure we can replicate the issue.  
http://www.pdfsharp.net/wiki/IssueSubmissions.ashx

**Comment by Prototipo-Erick-Santander** [comment]
Hello!
Where can I find the code for this?
