### ISSUE TITLE
Remove Dead Code

### ISSUE THREAD

**Issue by MovGP0** [empira/MigraDoc-1.5#17]
## Expected Behavior

Dead code should be removed from the code. This includes code that is commented using `//` or `#if false` statements, code that is unreachable, code that is not used like `using` statements and `this.XXX` statements, etc. 

## Actual Behavior

Lots of code that is not used at all and wastes lots of valuable develper time. 

## Steps to Reproduce the Behavior

Read the source code. Use Resharper and Roslynator to find code issues.

**Comment by ThomasHoevel** [comment]
The code has grown over a long time and "this." will be removed on revisions. Dead code will be removed on revisions when it is clear it is no longer useful.

**Comment by MovGP0** [comment]
code that is marked as `//` or `#if false` is NEVER useful. If you really need it in the future, Git does the job quite well.
